<?php

namespace Database\Seeders;

use App\Models\RequestType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RequestTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        RequestType::truncate();
        $data = [
            1 => [1, 1, "Routine Maintenance"],
            2 => [1, 1, "Emergency Shutdown"],
            3 => [1, 2, "Process Optimization"],
            4 => [1, 2, "Task Assignment"],
            5 => [1, 3, "Stock Replenishment"],
            6 => [1, 3, "Inventory Auditing"],
            7 => [1, 4, "Shift Planning"],
            8 => [1, 4, "Order Scheduling"],
            9 => [2, 5, "Incident Reporting"],
            10 => [2, 5, "Safety Audits"],
            11 => [2, 6, "Test Execution"],
            12 => [2, 6, "Test Result Analysis"],
            13 => [2, 7, "Daily Production Report"],
            14 => [2, 7, "Weekly Summary"],
            15 => [3, 8, "Equipment Allocation"],
            16 => [3, 8, "Training Request"],
            17 => [2, 9, "Quality Check"],
            18 => [2, 9, "Defect Reporting"],
            19 => [2, 10, "Protocol Development"],
            20 => [2, 10, "Protocol Review"],
            21 => [2, 11, "Issue Identification"],
            22 => [2, 11, "Corrective Action"],
            23 => [3, 12, "Calibration Scheduling"],
            24 => [3, 12, "Calibration Records"],
            25 => [2, 13, "Audit Scheduling"],
            26 => [2, 13, "Audit Findings"],
            27 => [6, 14, "Certification Request"],
            28 => [6, 14, "Training Session"],
            29 => [2, 15, "Document Review"],
            30 => [2, 15, "Document Update"],
            31 => [2, 16, "Supplier Audit"],
            32 => [2, 16, "Quality Agreement"],
            33 => [3, 17, "Maintenance Scheduling"],
            34 => [3, 17, "Maintenance Records"],
            35 => [3, 18, "Repair Request"],
            36 => [3, 18, "Fault Analysis"],
            37 => [3, 19, "Condition Monitoring"],
            38 => [3, 19, "Predictive Analysis"],
            39 => [3, 20, "Repair Request"],
            40 => [3, 20, "Repair Status Update"],
            41 => [3, 21, "Parts Request"],
            42 => [3, 21, "Parts Inventory Check"],
            43 => [5, 22, "Facility Maintenance"],
            44 => [5, 22, "Space Allocation"],
            45 => [5, 23, "Utility Monitoring"],
            46 => [5, 23, "Utility Billing"],
            47 => [5, 24, "Safety Inspections"],
            48 => [5, 24, "Safety Training"],
            49 => [4, 25, "Concept Development"],
            50 => [4, 25, "Prototype Testing"],
            51 => [4, 26, "Process Improvement"],
            52 => [4, 26, "Efficiency Analysis"],
            53 => [4, 27, "Material Testing"],
            54 => [4, 27, "Material Sourcing"],
            55 => [4, 28, "Tech Feasibility Study"],
            56 => [4, 28, "Tech Implementation"],
            57 => [4, 29, "Innovation Strategy"],
            58 => [4, 29, "Innovation Project"],
            59 => [4, 30, "Patent Filing"],
            60 => [4, 30, "Trademark Registration"],
            61 => [1, 31, "Project Planning"],
            62 => [1, 31, "Project Execution"],
            63 => [1, 32, "Partner Identification"],
            64 => [1, 32, "Partner Agreements"],
            65 => [5, 33, "Route Planning"],
            66 => [5, 33, "Shipment Tracking"],
            67 => [3, 34, "Inventory Control"],
            68 => [3, 34, "Stock Movement"],
            69 => [5, 35, "Warehouse Layout"],
            70 => [5, 35, "Warehouse Operations"],
            71 => [5, 36, "Supplier Orders"],
            72 => [5, 36, "Supplier Payments"],
            73 => [5, 37, "Order Processing"],
            74 => [5, 37, "Order Delivery"],
            75 => [5, 38, "Return Processing"],
            76 => [5, 38, "Return Authorization"],
            77 => [5, 39, "Customs Documentation"],
            78 => [5, 39, "Compliance Audits"],
            79 => [5, 40, "Vehicle Maintenance"],
            80 => [5, 40, "Fleet Scheduling"],
            81 => [6, 41, "Job Posting"],
            82 => [6, 41, "Candidate Screening"],
            83 => [6, 42, "Conflict Resolution"],
            84 => [6, 42, "Employee Feedback"],
            85 => [6, 43, "Training Needs Analysis"],
            86 => [6, 43, "Skill Development"],
            87 => [6, 44, "Salary Administration"],
            88 => [6, 44, "Benefits Enrollment"],
            89 => [6, 45, "Performance Reviews"],
            90 => [6, 45, "Performance Improvement Plans"],
            91 => [6, 46, "Policy Development"],
            92 => [6, 46, "Regulatory Compliance"],
            93 => [6, 47, "Record Maintenance"],
            94 => [6, 47, "Data Privacy"],
            95 => [6, 48, "Health Assessments"],
            96 => [6, 48, "Safety Protocols"],
            97 => [7, 49, "Market Analysis"],
            98 => [7, 49, "Competitor Analysis"],
            99 => [7, 50, "Ad Campaigns"],
            100 => [7, 50, "Ad Budgeting"],
            101 => [7, 51, "Sales Planning"],
            102 => [7, 51, "Sales Targeting"],
            103 => [7, 52, "Customer Feedback"],
            104 => [7, 52, "Customer Retention"],
            105 => [7, 53, "Promotional Events"],
            106 => [7, 53, "Promotional Material"],
            107 => [7, 54, "SEO Management"],
            108 => [7, 54, "Social Media Marketing"],
            109 => [7, 55, "Event Planning"],
            110 => [7, 55, "Event Coordination"],
            111 => [7, 56, "Lead Generation"],
            112 => [7, 56, "Sales Training"],
            113 => [8, 57, "Budget Forecasting"],
            114 => [8, 57, "Expense Tracking"],
            115 => [8, 58, "Financial Statements"],
            116 => [8, 58, "Variance Analysis"],
            117 => [8, 59, "Invoice Processing"],
            118 => [8, 59, "Vendor Payments"],
            119 => [8, 60, "Invoice Generation"],
            120 => [8, 60, "Payment Collection"],
            121 => [8, 61, "Tax Filing"],
            122 => [8, 61, "Tax Planning"],
            123 => [8, 62, "Payroll Processing"],
            124 => [8, 62, "Payroll Disbursement"],
            125 => [8, 63, "Audit Preparation"],
            126 => [8, 63, "Regulatory Reporting"],
            127 => [8, 64, "Investment Analysis"],
            128 => [8, 64, "Portfolio Management"],
        ];

        foreach ($data as $index => [$department,$category,$name]) {
            RequestType::create([
                'hash' => encrypt($index),
                'department_id' => $department,
                'category_id' => $category,
                'name' => $name,
                'is_active' => 1,
                'modified_by' => 'system',
            ]);
        }
    }
}
